baseURL = 'https://yboris.com/'
googleAnalytics = "G-GMST2VER92"
languageCode = 'en-us'
title = 'Boris Yakubchik'
disableKinds = ["taxonomy"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
[Params]
  images = ["img/social.png"]
  production = true
  description = "Personal website of Boris Yakubchik"