baseURL = 'https://yboris.com/'
googleAnalytics = "G-GMST2VER92"
languageCode = 'en-us'
title = 'Boris Yakubchik'
disableKinds = ["taxonomy", "taxonomyTerm"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true